# https://github.com/marketplace/actions/shell-linter
name: shell-linter
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          path: "oc-machine_resize"
